-- FSA unit batch: 50 original CFA Level 1-style questions, ids F01-F50.
-- Topics: Inventories (8), Long-Lived Assets (9), Income Taxes (8), Revenue Recognition (8), Ratio Analysis (10), Quality of Earnings (7).
-- Answer positions: index 0 = 17, index 1 = 17, index 2 = 16.
--
-- DIFFICULTY MIX DEVIATION -- READ BEFORE COPYING THIS AS A PATTERN.
-- This batch is 36% definitional/conceptual (18 items) / 38% single-step
-- calculation (19) / 26% multi-step-or-GAAP-vs-IFRS (13), against the usual
-- ~40/40/20 target in claude-code-spec.md section Authoring rules (rule 6).
-- The deviation is deliberate and was reviewed and approved by Kevin: FSA
-- tests GAAP-vs-IFRS discrimination heavily, and 6 of the 13 hard-bucket
-- items are GAAP-vs-IFRS pairs (F04, F12, F15, F16, F24, F29) that are worth
-- more than the conceptual items they would displace. The remaining 7 are
-- multi-step calculations (F10, F23, F25, F28, F38, F41, F47).
-- THIS IS NOT A PRECEDENT. Future batches should target ~40/40/20 unless the
-- same reasoning genuinely applies to that unit -- do not read 36/38/26 here
-- as the standard.
--
-- Every calculation was worked by hand and then independently recomputed from
-- each stem's raw numbers by a separate script (69 recomputations covering
-- both keys and distractor values, 0 failures). Kevin independently
-- re-verified 5 samples, including F15, which is correctly keyed to a $0
-- impairment loss (the US GAAP undiscounted-cash-flow recoverability screen
-- is passed at 420,000 > 400,000).
--
-- Rows are generated mechanically by scripts/gen-fsa-batch-migration.mjs from
-- .superpowers/sdd/task-6-batch-draft.json -- not hand-transcribed. Task 2's
-- seed migration drifted from its source in 11 of 36 rows precisely because
-- of hand-copying; see 20260730010233_fix_v1_seed_quote_drift.sql.

insert into questions (id, unit, topic, concept, stem, choices, answer, why) values
  ('F01', 'FSA', 'Inventories', 'Cost formulas', 'Under IFRS, which inventory cost formula is prohibited?', '["Specific identification","Weighted average cost","Last-in, first-out (LIFO)"]'::jsonb, 2, 'IAS 2 permits specific identification, FIFO, and weighted average cost, but bans LIFO; U.S. GAAP allows all four. Weighted average tempts because candidates recall that IFRS narrows the choice and assume the averaging method is the casualty.'),
  ('F02', 'FSA', 'Inventories', 'FIFO valuation', 'A wholesaler began the year with 200 units costing $10 each, then purchased 300 units at $12 and 500 units at $15. It sold 700 units during the year. Ending inventory under FIFO is:', '["$3,200","$3,930","$4,500"]'::jsonb, 2, '1,000 units were available and 700 sold, leaving 300 units; FIFO leaves the newest costs on the balance sheet, so 300 × $15 = $4,500. The $3,200 distractor is the LIFO answer (200 × $10 + 100 × $12) — under FIFO the oldest costs are the ones that left in COGS, not the ones that stayed.'),
  ('F03', 'FSA', 'Inventories', 'Cost flow methods', 'A distributor began the year with 400 units at $22, purchased 600 units at $25 in March and 500 units at $28 in September, and sold 1,100 units. Under FIFO, cost of goods sold is closest to:', '["$26,600","$27,720","$29,000"]'::jsonb, 0, 'FIFO expenses the oldest layers first: 400 × $22 + 600 × $25 + 100 × $28 = 8,800 + 15,000 + 2,800 = $26,600. The $29,000 distractor is LIFO (500 × $28 + 600 × $25) — in a rising-cost year LIFO always reports the higher COGS, which is the whole point of the choice.'),
  ('F04', 'FSA', 'Inventories', 'Cost and NRV', 'Under IFRS, inventories are measured at:', '["The lower of cost or market, where market is bounded by a ceiling and a floor","The lower of cost and net realizable value, with reversals of prior write-downs permitted","The lower of cost and net realizable value, with write-downs never reversed"]'::jsonb, 1, 'IAS 2 uses the lower of cost and net realizable value and requires reversal, capped at original cost, if NRV recovers. The no-reversal option describes U.S. GAAP, which treats a write-down as permanent — the single most-tested difference on inventory measurement.'),
  ('F05', 'FSA', 'Inventories', 'NRV write-down', 'An electronics retailer holds inventory that cost $180,000. Its estimated selling price is $195,000 and estimated costs to complete and sell it are $30,000. Under IFRS, the carrying amount reported is:', '["$180,000","$165,000","$195,000"]'::jsonb, 1, 'Net realizable value is 195,000 − 30,000 = $165,000, below the $180,000 cost, so inventory is written down to $165,000 and a $15,000 loss hits the income statement. The $180,000 answer tempts if you compare cost to the gross selling price and conclude there is no shortfall — selling costs must come out first.'),
  ('F06', 'FSA', 'Inventories', 'LIFO reserve', 'A U.S. filer reports LIFO inventory of $640,000 and discloses a LIFO reserve of $85,000, up from $70,000 a year earlier. Inventory restated to a FIFO basis is:', '["$555,000","$655,000","$725,000"]'::jsonb, 2, 'FIFO inventory = LIFO inventory + LIFO reserve = 640,000 + 85,000 = $725,000, because the reserve is the cumulative amount by which LIFO understates inventory. The $655,000 distractor adds only the $15,000 change in the reserve — that change is the adjustment to the year''s COGS, not to the inventory balance.'),
  ('F07', 'FSA', 'Inventories', 'Rising-price effects', 'In a period of rising inventory costs with stable quantities, a firm using LIFO rather than FIFO will report:', '["Higher COGS, lower net income, and lower ending inventory","Higher COGS, lower net income, and higher ending inventory","Lower COGS, higher net income, and lower ending inventory"]'::jsonb, 0, 'LIFO expenses the newest, most expensive units, so COGS is higher and net income lower, which leaves the old cheap costs sitting in ending inventory — lower inventory too. The second choice gets the income statement right but forgets that one pool of cost is split between COGS and inventory: what is expensed cannot also remain on the balance sheet.'),
  ('F08', 'FSA', 'Inventories', 'LIFO liquidation', 'A LIFO firm sells more units than it purchases during a year of rising costs. The most likely effect on the current year''s reported gross profit is:', '["An increase, because old low-cost layers are charged to COGS","A decrease, because the newest high-cost layers are charged to COGS","No effect, because LIFO always charges current costs to COGS"]'::jsonb, 0, 'When quantities decline, LIFO digs into old low-cost layers — a LIFO liquidation — understating COGS relative to current replacement cost and inflating gross profit unsustainably. The second choice states the normal LIFO result, which holds only while inventory quantities are stable or growing.'),
  ('F09', 'FSA', 'Long-Lived Assets', 'Capitalize vs expense', 'A manufacturer spends $90,000 replacing the roof on its factory, extending the building''s useful life by ten years. The most appropriate treatment is to:', '["Expense the $90,000 as repairs and maintenance in the current period","Capitalize the $90,000 and depreciate it over the extended life","Charge the $90,000 directly to retained earnings"]'::jsonb, 1, 'Expenditures that extend useful life or increase capacity are capitalized and depreciated; routine repairs that merely maintain the asset are expensed. Expensing tempts because the cash leaves now, but that would understate current income and overstate later income relative to the economics.'),
  ('F10', 'FSA', 'Long-Lived Assets', 'Declining balance', 'A machine costs $500,000, has a $50,000 residual value, and an 8-year useful life. Under the double-declining-balance method, depreciation expense in year 2 is closest to:', '["$93,750","$112,500","$125,000"]'::jsonb, 0, 'The DDB rate is 2/8 = 25% applied to declining book value, ignoring residual value in the base: year 1 = 500,000 × 25% = $125,000, leaving book value of $375,000, so year 2 = 375,000 × 25% = $93,750. The $112,500 distractor subtracts residual value first — that step belongs to straight-line, not to a declining-balance rate.'),
  ('F11', 'FSA', 'Long-Lived Assets', 'Units of production', 'A printing press costs $340,000, has a $40,000 residual value, and is expected to produce 1,500,000 units over its life. It produced 210,000 units this year. Depreciation expense for the year is:', '["$47,600","$42,000","$53,200"]'::jsonb, 1, 'The depreciable base is 340,000 − 40,000 = $300,000, or $0.20 per unit, so 210,000 × 0.20 = $42,000. The $47,600 distractor divides the full $340,000 cost by expected output — forgetting residual value, the same trap that makes straight-line questions bite.'),
  ('F12', 'FSA', 'Long-Lived Assets', 'Revaluation model', 'A company applies the revaluation model to a class of PP&E whose fair value has risen above carrying amount for the first time. Under IFRS, the increase is:', '["Recognized in net income as a gain","Recognized in other comprehensive income as a revaluation surplus","Not permitted to be recognized under any circumstances"]'::jsonb, 1, 'A first-time upward revaluation goes to other comprehensive income as revaluation surplus; only the portion reversing a revaluation decrease previously charged to profit or loss reaches net income. The not-permitted option describes U.S. GAAP, which has no revaluation model for PP&E at all — the discrimination being tested.'),
  ('F13', 'FSA', 'Long-Lived Assets', 'Asset disposal', 'Equipment that originally cost $250,000 and has accumulated depreciation of $180,000 is sold for $85,000. The company reports:', '["A gain of $15,000","A gain of $85,000","A loss of $165,000"]'::jsonb, 0, 'Carrying value is 250,000 − 180,000 = $70,000, so proceeds of $85,000 produce a $15,000 gain. The $165,000 loss compares proceeds to original cost and ignores accumulated depreciation, which has already been charged to income across prior years.'),
  ('F14', 'FSA', 'Long-Lived Assets', 'Capitalized interest', 'A company constructs a warehouse for its own use over two years, financing the build with debt. Interest incurred during the construction period is most appropriately:', '["Expensed as incurred, because interest is a financing cost","Capitalized as part of the cost of the warehouse","Recorded as a reduction of shareholders equity"]'::jsonb, 1, 'Interest on funds borrowed to construct an asset for the firm''s own use is capitalized into the asset''s cost and charged to income later as depreciation. Expensing tempts because interest is a financing cost everywhere else — but here it is a cost of getting the asset ready for use, and capitalizing it flatters both reported interest coverage and operating cash flow.'),
  ('F15', 'FSA', 'Long-Lived Assets', 'Impairment testing', 'A U.S. GAAP filer holds a machine with a carrying amount of $400,000. Undiscounted expected future cash flows from the machine are $420,000 and its fair value is $310,000. The impairment loss recognized is:', '["$110,000","$90,000","$0"]'::jsonb, 2, 'Under U.S. GAAP an asset held for use fails the recoverability test only if carrying amount exceeds undiscounted expected cash flows; $420,000 exceeds $400,000, so no loss is recorded. The $90,000 distractor jumps straight to the fair-value measurement step — which is exactly how IFRS handles it, comparing carrying amount to recoverable amount in one step.'),
  ('F16', 'FSA', 'Long-Lived Assets', 'Impairment reversal', 'An asset held for use was written down for impairment in a prior year, and its recoverable amount has since increased. Reversal of that impairment loss is:', '["Permitted under IFRS, capped at the carrying amount that would have existed absent the impairment, and prohibited under U.S. GAAP","Prohibited under both IFRS and U.S. GAAP","Permitted under both, with the reversal reported in other comprehensive income"]'::jsonb, 0, 'IFRS allows reversal through profit or loss up to the depreciated original carrying amount; U.S. GAAP treats the written-down figure as a new cost basis and never reverses. Prohibited-under-both tempts because the U.S. GAAP rule is the stricter and more memorable one, so candidates over-apply it.'),
  ('F17', 'FSA', 'Long-Lived Assets', 'Useful life estimates', 'A firm lengthens the estimated useful lives of its depreciable assets. Holding all else constant, the immediate effects are:', '["Lower depreciation expense, higher net income, and higher reported total asset turnover","Lower depreciation expense, higher net income, and lower reported total asset turnover","Higher depreciation expense, lower net income, and higher reported total asset turnover"]'::jsonb, 1, 'A longer life spreads the same cost over more years, so annual depreciation falls and net income rises; because accumulated depreciation builds more slowly, average total assets are larger and revenue divided by assets falls. The first choice gets the income effect right but misses that slower depreciation leaves a bigger denominator in the turnover ratio.'),
  ('F18', 'FSA', 'Income Taxes', 'Deferred tax liabilities', 'A deferred tax liability most commonly arises when:', '["Tax depreciation exceeds financial-reporting depreciation in the early years of an asset''s life","Financial-reporting depreciation exceeds tax depreciation in the early years of an asset''s life","A company recognizes warranty expense before the related cash is paid"]'::jsonb, 0, 'Accelerated tax depreciation makes taxable income lower than pre-tax accounting income now and higher later, creating a liability for taxes deferred to future periods. The warranty choice is the mirror image — an expense recognized for books before it is deductible for tax — which produces a deferred tax asset.'),
  ('F19', 'FSA', 'Income Taxes', 'Temporary differences', 'An asset originally cost $600,000. After two years its carrying amount for financial reporting is $480,000 and its tax base is $384,000. At a 25% tax rate, the deferred tax liability is:', '["$96,000","$54,000","$24,000"]'::jsonb, 2, 'The temporary difference is 480,000 − 384,000 = $96,000, and the DTL is that difference tax-effected: 96,000 × 25% = $24,000. The $96,000 distractor reports the temporary difference itself — a deferred tax balance is always the difference multiplied by the rate, never the raw gap.'),
  ('F20', 'FSA', 'Income Taxes', 'Tax expense', 'Taxes payable for the year are $310,000. The deferred tax liability rose from $70,000 to $95,000 and the deferred tax asset was unchanged. Income tax expense is:', '["$285,000","$335,000","$405,000"]'::jsonb, 1, 'Income tax expense = current tax payable + the increase in net deferred tax liability = 310,000 + (95,000 − 70,000) = $335,000. The $405,000 distractor adds the entire $95,000 DTL balance rather than the year''s change — only the movement belongs in this year''s expense.'),
  ('F21', 'FSA', 'Income Taxes', 'Effective tax rate', 'A firm reports pre-tax accounting income of $1,200,000 and income tax expense of $252,000. Its statutory rate is 25%. Its effective tax rate is closest to:', '["25.0%","21.0%","26.6%"]'::jsonb, 1, 'Effective tax rate = income tax expense / pre-tax accounting income = 252,000 / 1,200,000 = 21.0%. The 25% choice is the statutory rate, and the gap between the two is the useful signal — it is created by permanent differences such as tax credits or tax-exempt income.'),
  ('F22', 'FSA', 'Income Taxes', 'Valuation allowance', 'Under U.S. GAAP, a valuation allowance is recorded against a deferred tax asset when:', '["It is more likely than not that some portion of the deferred tax asset will not be realized","The enacted statutory tax rate is expected to decline","The deferred tax asset exceeds the deferred tax liability"]'::jsonb, 0, 'The allowance is a judgment about realizability — it reduces the DTA when future taxable income is unlikely to be sufficient, and releasing it later boosts earnings, which makes it a favored earnings-management lever. A rate decline does shrink the DTA, but that is a remeasurement of the asset itself, not a valuation allowance.'),
  ('F23', 'FSA', 'Income Taxes', 'Tax rate changes', 'A firm carries a deferred tax liability of $180,000 measured at a 30% enacted rate. Legislation immediately reduces the enacted rate to 21%. The most likely effect on the current-year income statement is:', '["A $54,000 increase in income tax expense","No income statement effect; the adjustment goes to other comprehensive income","A $54,000 decrease in income tax expense"]'::jsonb, 2, 'The DTL is remeasured at the new rate — 180,000 × 21/30 = $126,000 — and the $54,000 write-down runs through deferred tax expense, lowering total tax expense and raising net income. The increase option reflects the instinct that a tax-law change is bad news; for a firm with a net DTL, a rate cut is a one-time earnings benefit.'),
  ('F24', 'FSA', 'Income Taxes', 'Deferred tax presentation', 'Under IFRS, deferred tax assets and liabilities are presented on the balance sheet as:', '["Always non-current","Current or non-current, based on the classification of the underlying asset or liability","Always current"]'::jsonb, 0, 'IAS 12 requires every deferred tax balance to be non-current, and current U.S. GAAP reaches the same answer. Classifying by the underlying item is the intuitive rule — and it was the U.S. GAAP rule before the 2015 simplification — which is why it still draws candidates in.'),
  ('F25', 'FSA', 'Income Taxes', 'Taxes payable', 'A company reports pre-tax accounting income of $500,000, which includes $40,000 of permanently tax-exempt municipal bond interest. Tax depreciation exceeds book depreciation by $75,000. At a 25% tax rate, taxes payable for the year are:', '["$125,000","$115,000","$96,250"]'::jsonb, 2, 'Taxable income = 500,000 − 40,000 exempt interest − 75,000 extra tax depreciation = $385,000, so taxes payable = 385,000 × 25% = $96,250. The $115,000 distractor removes only the permanent difference — but taxes payable is computed on taxable income, which reflects temporary differences too; it is tax expense that ignores them.'),
  ('F26', 'FSA', 'Revenue Recognition', 'Five-step model', 'In the five-step revenue model, determining the transaction price comes immediately after:', '["Identifying the performance obligations in the contract","Identifying the contract with the customer","Allocating the transaction price to the performance obligations"]'::jsonb, 0, 'The sequence is: identify the contract, identify the performance obligations, determine the transaction price, allocate it to the obligations, then recognize revenue as each is satisfied. Allocation tempts because it also involves the transaction price — but you cannot allocate a price you have not yet determined.'),
  ('F27', 'FSA', 'Revenue Recognition', 'Price allocation', 'A software firm sells a bundle for $60,000 comprising a perpetual license (standalone price $50,000) delivered immediately and two years of support (standalone price $30,000) provided over time. Revenue recognized at delivery is:', '["$60,000","$50,000","$37,500"]'::jsonb, 2, 'The transaction price is allocated in proportion to standalone selling prices: 50,000 / 80,000 = 62.5%, so 62.5% × 60,000 = $37,500 is recognized on the license. The $50,000 answer uses the standalone price directly and ignores the bundle discount, which must be shared across both obligations.'),
  ('F28', 'FSA', 'Revenue Recognition', 'Percentage of completion', 'A contractor signs a $4,000,000 fixed-price contract with total expected costs of $3,200,000. Costs incurred to date are $1,200,000. Under the cost-to-cost input method, revenue recognized to date is:', '["$300,000","$1,200,000","$1,500,000"]'::jsonb, 2, 'Progress is 1,200,000 / 3,200,000 = 37.5%, so revenue to date is 37.5% × 4,000,000 = $1,500,000. The $300,000 distractor is the gross profit recognized to date (1,500,000 − 1,200,000) — a revenue-versus-profit mix-up that costs marks in every vignette.'),
  ('F29', 'FSA', 'Revenue Recognition', 'Cost recovery', 'A construction firm cannot reliably measure its progress toward completing a long-term contract, though it expects to recover its costs. Under IFRS, it recognizes:', '["No revenue until the contract is complete","Revenue equal to the costs incurred, with no profit until the outcome becomes measurable","The full contract price immediately, with a provision for the uncertainty"]'::jsonb, 1, 'IFRS applies a cost-recovery approach: revenue equal to recoverable costs incurred, so zero profit is reported until progress can be measured reliably. Waiting for completion is the old completed-contract method, permitted under legacy U.S. GAAP but never under IFRS, and eliminated by the converged standard.'),
  ('F30', 'FSA', 'Revenue Recognition', 'Principal vs agent', 'An online marketplace never takes control of the goods listed on it and earns a 12% commission on each $200 sale. Per sale, it should report revenue of:', '["$176","$200","$24"]'::jsonb, 2, 'An entity that does not obtain control of the goods is an agent and reports only its commission — 12% × 200 = $24 — as revenue. Reporting the gross $200 is the classic principal-versus-agent overstatement: it inflates revenue and revenue growth while leaving net income completely unchanged.'),
  ('F31', 'FSA', 'Revenue Recognition', 'Variable consideration', 'A vendor''s $500,000 contract includes a $50,000 bonus if delivery beats a deadline. The vendor estimates a 60% probability of earning the bonus and uses the expected value method. The transaction price is:', '["$500,000","$530,000","$550,000"]'::jsonb, 1, 'Variable consideration enters the transaction price at its expected value when a range of outcomes exists: 500,000 + (0.60 × 50,000) = $530,000, subject to the constraint that a significant revenue reversal is not probable. Excluding the bonus entirely treats uncertain as ignore, which the standard rejects — uncertainty is estimated, not deferred.'),
  ('F32', 'FSA', 'Revenue Recognition', 'Over-time recognition', 'Revenue from a performance obligation is recognized over time rather than at a point in time when:', '["The customer simultaneously receives and consumes the benefits as the entity performs","The contract spans more than one accounting period","The customer pays for the contract in installments over its term"]'::jsonb, 0, 'Over-time recognition depends on the pattern of control transfer — the customer consuming as the entity performs, the entity enhancing an asset the customer controls, or an asset with no alternative use plus an enforceable right to payment. Contract length is irrelevant: a two-year contract with a single delivery at the end is still point-in-time.'),
  ('F33', 'FSA', 'Revenue Recognition', 'Consignment sales', 'A manufacturer ships goods to a distributor on consignment, and the distributor may return anything it does not sell. The manufacturer should recognize revenue:', '["When the goods are shipped to the distributor","When the distributor sells the goods to an end customer","Ratably over the consignment period"]'::jsonb, 1, 'Control has not transferred on shipment — the distributor bears no risk and can return the goods — so revenue waits for the sale to the end customer. Recognizing at shipment is the error behind many channel-stuffing restatements, and it tempts because the physical goods have visibly left the building.'),
  ('F34', 'FSA', 'Ratio Analysis', 'Inventory turnover', 'Cost of goods sold is $1,800,000, beginning inventory is $260,000, and ending inventory is $340,000. Days of inventory on hand, using a 365-day year, is closest to:', '["53 days","61 days","69 days"]'::jsonb, 1, 'Inventory turnover uses average inventory: 1,800,000 / [(260,000 + 340,000)/2] = 1,800,000 / 300,000 = 6.0 times, so days of inventory on hand = 365 / 6.0 = 61 days. The 69-day answer divides by ending inventory alone, which understates turnover whenever inventory is growing.'),
  ('F35', 'FSA', 'Ratio Analysis', 'Cash conversion cycle', 'A firm reports days of inventory on hand of 58, days of sales outstanding of 42, and 35 days of payables. Its cash conversion cycle is:', '["65 days","51 days","135 days"]'::jsonb, 0, 'Cash conversion cycle = DOH + DSO − days of payables = 58 + 42 − 35 = 65 days, the time cash is tied up between paying suppliers and collecting from customers. The 135-day answer adds all three; payables are subtracted because supplier credit funds part of the cycle for free.'),
  ('F36', 'FSA', 'Ratio Analysis', 'DuPont analysis', 'A company has a net profit margin of 8%, total asset turnover of 1.5, and a financial leverage ratio (average assets / average equity) of 2.0. Its return on equity is:', '["12%","16%","24%"]'::jsonb, 2, 'Three-part DuPont: ROE = net profit margin × total asset turnover × leverage = 0.08 × 1.5 × 2.0 = 24%. The 12% distractor stops at ROA (margin × turnover) and omits leverage — the step that converts a return on the whole asset base into a return to shareholders alone.'),
  ('F37', 'FSA', 'Ratio Analysis', 'ROE decomposition', 'Two firms report identical return on assets, but Firm A reports a higher return on equity. Using the DuPont decomposition, the difference must come from:', '["A higher net profit margin at Firm A","A higher total asset turnover at Firm A","A higher financial leverage ratio at Firm A"]'::jsonb, 2, 'ROE = ROA × financial leverage, so if ROA is identical the entire gap is leverage. Margin and turnover tempt because they do drive ROE — but they are precisely the two components that multiply to ROA, which the question already fixes as equal.'),
  ('F38', 'FSA', 'Ratio Analysis', 'Interest coverage', 'A firm reports EBIT of $2,400,000 and interest expense of $600,000, and it capitalized a further $150,000 of interest during the year. The interest coverage ratio that best reflects the firm''s total interest burden is:', '["3.2×","3.75×","4.0×"]'::jsonb, 0, 'Capitalized interest never reaches the income statement, so total interest incurred is 600,000 + 150,000 = $750,000 and coverage is 2,400,000 / 750,000 = 3.2×. The 4.0× figure is what the statements show as reported — which is exactly why analysts add capitalized interest back before comparing leveraged firms.'),
  ('F39', 'FSA', 'Ratio Analysis', 'Days sales outstanding', 'A company reports revenue of $7,300,000, cost of goods sold of $5,110,000, and average accounts receivable of $584,000. Days of sales outstanding is closest to:', '["12.5 days","29.2 days","41.7 days"]'::jsonb, 1, 'Receivables turnover = 7,300,000 / 584,000 = 12.5 times, so DSO = 365 / 12.5 = 29.2 days. The 12.5-day answer reports the turnover figure itself as days — the same unit confusion that makes candidates hand back a ratio when the question asked for a period.'),
  ('F40', 'FSA', 'Ratio Analysis', 'Comparability limits', 'An analyst compares a U.S. LIFO firm with an otherwise identical IFRS firm using FIFO during a period of rising costs. The LIFO firm''s reported inventory turnover will be:', '["Higher, because LIFO raises COGS and lowers reported inventory","Lower, because LIFO raises reported inventory","Identical, because the cost formula affects only the balance sheet"]'::jsonb, 0, 'LIFO charges the newest, highest costs to COGS while leaving old cheap costs in inventory, so the numerator rises as the denominator falls and turnover looks better with no operating improvement. The identical option forgets that a cost formula splits one pool of cost between the income statement and the balance sheet, so it must move both.'),
  ('F41', 'FSA', 'Ratio Analysis', 'Operating margin', 'Revenue is $5,000,000, COGS $3,100,000, SG&A $900,000, depreciation $400,000, interest expense $150,000, and the tax rate is 25%. The operating profit margin is:', '["6.75%","9.0%","12.0%"]'::jsonb, 2, 'Operating margin stops at operating income, before interest and taxes: (5,000,000 − 3,100,000 − 900,000 − 400,000) / 5,000,000 = 600,000 / 5,000,000 = 12.0%. The 9.0% choice subtracts interest, which produces the pre-tax margin; operating margin is deliberately capital-structure-neutral so firms with different debt loads stay comparable.'),
  ('F42', 'FSA', 'Ratio Analysis', 'Sustainable growth', 'A firm earns a return on equity of 18% and pays out 40% of net income as dividends. Its sustainable growth rate is:', '["7.2%","10.8%","18.0%"]'::jsonb, 1, 'Sustainable growth = ROE × retention ratio = 18% × (1 − 0.40) = 10.8%, the rate equity can grow on internally generated funds alone. The 7.2% distractor multiplies by the payout ratio instead — dividends paid out are precisely the earnings that cannot fund growth.'),
  ('F43', 'FSA', 'Ratio Analysis', 'Leverage ratios', 'A company has total debt of $600,000 and shareholders equity of $1,500,000. It then repurchases $300,000 of its own stock for cash. Its debt-to-equity ratio moves from:', '["0.40 to 0.50","0.40 to 0.33","0.40 to 0.40, since a buyback affects only assets"]'::jsonb, 0, 'The buyback cuts cash and equity by $300,000 while leaving debt untouched: 600,000 / 1,200,000 = 0.50, up from 600,000 / 1,500,000 = 0.40. The no-effect choice forgets that a repurchase is funded out of equity, so every dollar returned to shareholders shrinks the ratio''s denominator.'),
  ('F44', 'FSA', 'Quality of Earnings', 'Accrual quality', 'A company reports rapidly rising net income while its operating cash flow declines. This divergence most likely signals:', '["Improving earnings quality, because accruals correctly anticipate future cash","A high accrual component in earnings, which tends to predict weaker future earnings","Nothing about earnings quality, because the two figures are computed on unrelated bases"]'::jsonb, 1, 'A widening gap between accrual earnings and operating cash flow means income rests on estimates and timing rather than collected cash, and high-accrual earnings are empirically less persistent. The last choice tempts because the two measures do differ by construction — but they must converge over time, so a persistent gap is a warning, not an artifact.'),
  ('F45', 'FSA', 'Quality of Earnings', 'Accruals ratio', 'Net income is $480,000, operating cash flow is $300,000, investing cash flow is negative $120,000, and average net operating assets are $3,000,000. The cash-flow-basis aggregate accruals ratio is:', '["6%","10%","16%"]'::jsonb, 1, 'Aggregate accruals = net income − (CFO + CFI) = 480,000 − (300,000 − 120,000) = $300,000, and the ratio is 300,000 / 3,000,000 = 10%; higher means lower earnings quality. The 6% distractor omits investing cash flow, but capital spending and its non-cash counterpart, depreciation, are part of the accrual and belong in the measure.'),
  ('F46', 'FSA', 'Quality of Earnings', 'Cash flow classification', 'A firm begins reporting costs it previously treated as operating outflows as capital expenditures instead. The effect on its reported cash flows is:', '["Operating cash flow rises and investing cash flow falls, with no change in total cash flow","Operating cash flow and total cash flow both rise","Operating cash flow falls and investing cash flow rises"]'::jsonb, 0, 'Capitalizing an operating cost moves the same cash outflow from CFO to CFI, so operating cash flow improves while total cash is unchanged — a favored way to dress up cash-flow quality. The second choice tempts if you notice only the CFO improvement and forget that cash out the door is still cash out the door.'),
  ('F47', 'FSA', 'Quality of Earnings', 'Capitalization effects', 'A firm spends $900,000 on software development. Compared with expensing it immediately, capitalizing the cost and amortizing it straight-line over three years (with a full year of amortization in year 1) makes year-1 pre-tax income higher by:', '["$300,000","$900,000","$600,000"]'::jsonb, 2, 'Expensing charges the full $900,000 to year 1, while capitalizing charges only 900,000 / 3 = $300,000 of amortization, so pre-tax income is $600,000 higher. The $900,000 answer forgets that capitalizing still triggers amortization in year 1 — the benefit is deferring two-thirds of the cost, not all of it.'),
  ('F48', 'FSA', 'Quality of Earnings', 'Receivables red flags', 'A company''s revenue grew 20% while its days of sales outstanding rose from 38 days to 61 days. The most likely interpretation is:', '["Growth is being purchased with looser credit terms or channel stuffing, so its quality is low","Collections improved, which confirms the strength of the revenue growth","Revenue quality is unaffected, because DSO measures inventory rather than receivables"]'::jsonb, 0, 'Receivables growing far faster than sales means the reported revenue has not been collected — the signature of pulling sales forward with easy credit or stuffing the distribution channel. The improved-collections choice inverts the ratio: rising DSO means customers are paying more slowly, not faster.'),
  ('F49', 'FSA', 'Quality of Earnings', 'Non-recurring items', 'A firm reports a large gain on the sale of a division inside operating income. For forecasting purposes, an analyst should:', '["Include the gain, since management classified it as operating","Exclude the gain and also remove an equivalent amount from the prior year for comparability","Exclude the gain from sustainable earnings while noting the classification choice itself as a warning sign"]'::jsonb, 2, 'A one-time divestiture gain is not repeatable, so it comes out of the earnings base used to forecast, and its placement inside operating income is itself a quality flag. The prior-year adjustment sounds rigorous but fabricates an item that never occurred; comparability comes from removing actual non-recurring items in the years they arose.'),
  ('F50', 'FSA', 'Quality of Earnings', 'Reserve management', 'A company sharply increases its allowance for doubtful accounts in a weak year, then releases part of that allowance in the following strong year. The effect across the two years is:', '["No effect on either year, since the allowance is a balance sheet account","Higher reported income in the weak year and lower reported income in the strong year","Lower reported income in the weak year and higher reported income in the strong year, smoothing the reported trend"]'::jsonb, 2, 'Over-provisioning raises bad debt expense and depresses the weak year, and releasing the excess later reduces expense and lifts the strong year — the classic cookie-jar reserve that flatters the earnings trend. The no-effect choice forgets that every change in the allowance runs through bad debt expense on the income statement.');
